### ISSUE TITLE
Should we use go modules?

### ISSUE THREAD

**Issue by claucece** [privacypass/challenge-bypass-server#15]
With the recent push for more usage of go modules in go 1.16, should we use modules?

@alxdavids @armfazh

**Comment by bob1985-virus** [comment]
Please transfer to my account ambank 2340020108583 bob Azahary thanks

**Comment by Lekensteyn** [comment]
Go modules seems to make sense.

(BTW I reported the previous comment as spam, hopefully it will be deleted automatically when GitHub support replies.)

**Comment by claucece** [comment]
@Lekensteyn Thank you! I also reported it. Hopefully, it will be removed ;)
