### ISSUE TITLE
A plan to do smooth key rotation

### ISSUE THREAD

**Issue by lziest** [privacypass/challenge-bypass-server#3]
This should be coordinated with plugin update. As a primitive design I have, plugin could/should read the server commitment from a endpoint, so we can update the commitment at any time. On the other hand, the server should have capability to keep a list of old private keys for token redemption.

**Comment by alxdavids** [comment]
The final stage of the implementation is handled in #7

**Comment by alxdavids** [comment]
The server-side support for this is now completed since #7 was merged.
